FROM python:3.10-slim


WORKDIR /app

Copy ./src /app


RUN pip install --no-cache-dir -r requirements.txt


Expose 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]